version: '2.0'
events:
  CI_BLOCK:
    chains:
    - why-ci-blocked
  CODEBAN:
    chains:
    - why-code-violation
  SCORE_LOW:
    chains:
    - why-score-low
  DECISION:
    chains:
    - why-decision
