#!/usr/bin/env python3
"""QA AI 集成 — 让 AI 自动读 QA 报告、自动修代码、自动验证。

三个能力：
  1. integrate — 将 CLAUDE.md 注入 AI 工具（Cursor/Copilot/Claude Code）
  2. handoff   — Gate DENY 时，生成 AI 可直接消费的修复上下文
  3. fix-loop  — 自动循环：AI 修 → QA 验 → 直到过
"""
import os, json, sys, subprocess
from datetime import datetime
from typing import List, Tuple

_SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_SCRIPTS_DIR)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)


def integrate(project_root: str = _PROJECT_ROOT):
    """将 QA CLAUDE.md 注入 AI 工具配置"""
    results = []

    # 源文件
    src = os.path.join(project_root, ".ai/prompts/CLAUDE.md")
    if not os.path.exists(src):
        return [("error", "CLAUDE.md 不存在 — 请先运行 qa plan init")]

    # 1. Cursor — .cursorrules
    cursor_dst = os.path.join(project_root, ".cursorrules")
    if not os.path.exists(cursor_dst):
        with open(cursor_dst, "w", encoding="utf-8") as f:
            f.write(open(src, encoding="utf-8").read())
        results.append(("ok", "Cursor: 已写入 .cursorrules"))
    else:
        results.append(("skip", "Cursor: .cursorrules 已存在"))

    # 2. Copilot — .github/copilot-instructions.md
    copilot_dir = os.path.join(project_root, ".github")
    os.makedirs(copilot_dir, exist_ok=True)
    copilot_dst = os.path.join(copilot_dir, "copilot-instructions.md")
    if not os.path.exists(copilot_dst):
        with open(copilot_dst, "w", encoding="utf-8") as f:
            content = "# Copilot Instructions\n\n"
            content += open(src, encoding="utf-8").read()
            content += "\n\n## QA Handoff\n"
            content += "When QA check fails:\n"
            content += "1. Read .ai/fixes/pending.json\n"
            content += "2. Fix issues listed there\n"
            content += "3. Run `python scripts/qa_check.py health`\n"
            content += "4. Repeat until all pass\n"
            f.write(content)
        results.append(("ok", "Copilot: 已写入 .github/copilot-instructions.md"))
    else:
        results.append(("skip", "Copilot: 已存在"))

    # 3. Claude Code — 项目根 CLAUDE.md
    claude_dst = os.path.join(project_root, "CLAUDE.md")
    if not os.path.exists(claude_dst) and os.path.exists(src):
        # 软链或复制
        with open(claude_dst, "w", encoding="utf-8") as f:
            content = open(src, encoding="utf-8").read()
            content += "\n\n---\n*Auto-generated by QA AI Integration*\n"
            f.write(content)
        results.append(("ok", "Claude Code: 已写入 CLAUDE.md"))
    else:
        results.append(("skip", "Claude Code: 已存在"))

    return results


def handoff(project_root: str = _PROJECT_ROOT) -> str:
    """Gate DENY 时生成 AI 可直接消费的修复上下文文件
    
    输出: .ai/handoff/latest.json — AI 读这个就知道要修什么
    """
    report_path = os.path.join(project_root, ".ai/logs/qa-report.json")
    pending_path = os.path.join(project_root, ".ai/fixes/pending.json")

    if not os.path.exists(report_path):
        return "无 QA 报告"

    with open(report_path, "r", encoding="utf-8") as f:
        report = json.load(f)

    pending_tasks = []
    if os.path.exists(pending_path):
        with open(pending_path, "r", encoding="utf-8") as f:
            pdata = json.load(f)
        pending_tasks = pdata.get("classified_tasks", pdata.get("pending", []))

    # 构建 AI 上下文
    context = {
        "timestamp": datetime.now().isoformat(),
        "system": "QA Gate handoff — AI 请根据此上下文修复代码",
        "instructions": [
            "1. 读取下方 failure_context 中的问题列表",
            "2. 对每个问题，按 fix_guide 指导修复",
            "3. 修复后运行: python scripts/qa_check.py health",
            "4. 如果仍有问题，重新读取本文件继续修复",
            "5. 直至 errors=0 再提交",
        ],
        "failure_context": {
            "total_errors": report.get("errors", 0),
            "blocked": report.get("blocked", False),
            "tasks": [],
        },
    }

    # 合并 checker 结果到任务列表
    for cid, cdata in report.get("checkers", {}).items():
        if cdata.get("skipped") or cdata.get("errors", 0) == 0:
            continue
        for issue in cdata.get("issues", []):
            task = {
                "checker": cid,
                "issue": issue,
                "severity": "BLOCKER" if cid not in ("quality_gates", "claude_validation") else "WARN",
            }
            # 如果有分类指导，加上
            for pt in pending_tasks:
                if pt.get("message", "")[:50] in issue:
                    task["fix_guide"] = pt.get("fix_guide", "")
                    task["effort"] = pt.get("effort", "")
            context["failure_context"]["tasks"].append(task)

    # 保存 handoff
    handoff_dir = os.path.join(project_root, ".ai/handoff")
    os.makedirs(handoff_dir, exist_ok=True)
    handoff_path = os.path.join(handoff_dir, "latest.json")
    with open(handoff_path, "w", encoding="utf-8") as f:
        json.dump(context, f, ensure_ascii=False, indent=2)

    return handoff_path


def fix_loop(project_root: str = _PROJECT_ROOT, max_iterations: int = 5) -> list:
    """自动修复循环：AI 修 → QA 验 → 直到过
    
    注意：这只是一个自动化框架，实际的 AI 修复需要 AI agent 实现。
    本函数执行的是：生成 handoff → 等待 AI 修 → 重新检查 → 判断
    """
    iterations = []
    for i in range(max_iterations):
        # 生成 handoff
        handoff_path = handoff(project_root)
        
        # 运行 QA
        result = subprocess.run(
            [sys.executable, os.path.join(_SCRIPTS_DIR, "qa_check.py"), "health"],
            capture_output=True, cwd=project_root, timeout=60,
        )
        report_path = os.path.join(project_root, ".ai/logs/qa-report.json")
        
        iterations.append({
            "iteration": i + 1,
            "handoff": handoff_path,
            "qa_exit": result.returncode,
            "timestamp": datetime.now().isoformat(),
        })

        # 检查是否通过
        if os.path.exists(report_path):
            with open(report_path, "r", encoding="utf-8") as f:
                report = json.load(f)
            if report.get("errors", 0) == 0:
                iterations[-1]["status"] = "PASS"
                break
            else:
                iterations[-1]["status"] = f"FAIL ({report['errors']} errors)"
        else:
            iterations[-1]["status"] = "UNKNOWN"

        # 如果不是最后一次，等待 AI 修复（这里只是记录 handoff 位置）
        if i < max_iterations - 1:
            iterations[-1]["waiting_for_ai"] = f"AI 请读取 {handoff_path} 修复问题"

    return iterations


def status(project_root: str = _PROJECT_ROOT) -> dict:
    """检查 AI 集成状态"""
    result = {}
    for name, path in [
        ("Cursor", ".cursorrules"),
        ("Copilot", ".github/copilot-instructions.md"),
        ("Claude Code", "CLAUDE.md"),
        ("QA CLAUDE", ".ai/prompts/CLAUDE.md"),
    ]:
        full = os.path.join(project_root, path)
        result[name] = "已集成" if os.path.exists(full) else "未集成"

    # 检查 handoff 文件
    handoff_path = os.path.join(project_root, ".ai/handoff/latest.json")
    if os.path.exists(handoff_path):
        with open(handoff_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        result["Last handoff"] = f"{data.get('timestamp','')} — {len(data.get('failure_context',{}).get('tasks',[]))} tasks"
    else:
        result["Last handoff"] = "无"

    return result


def main():
    import argparse
    parser = argparse.ArgumentParser(description="QA AI 集成")
    parser.add_argument("action", nargs="?", default="status",
                        choices=["integrate", "handoff", "fix-loop", "status"])
    parser.add_argument("--max-iterations", type=int, default=5)
    args = parser.parse_args()

    if args.action == "integrate":
        results = integrate()
        print("=== AI 集成结果 ===")
        for status_type, msg in results:
            icon = {"ok": "✅", "skip": "⏭️", "error": "❌"}.get(status_type, "?")
            print(f"  {icon} {msg}")

    elif args.action == "handoff":
        path = handoff()
        print(f"AI handoff 已生成: {path}")
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        tasks = data.get("failure_context", {}).get("tasks", [])
        print(f"  待修复: {len(tasks)} 项")
        for t in tasks[:5]:
            print(f"    [{t['severity']}] {t['checker']}: {t['issue'][:80]}")
        if len(tasks) > 5:
            print(f"    ... 共 {len(tasks)} 项")

    elif args.action == "fix-loop":
        print("=== 自动修复循环 ===")
        iters = fix_loop(max_iterations=args.max_iterations)
        for it in iters:
            print(f"  Iteration {it['iteration']}: {it.get('status','...')}")
        last = iters[-1] if iters else {}
        if last.get("status") == "PASS":
            print("✅ 修复循环通过")
        else:
            print(f"❌ 修复循环未完成: {last.get('status', 'unknown')}")

    elif args.action == "status":
        s = status()
        print("=== AI 集成状态 ===")
        for k, v in s.items():
            icon = "✅" if "集成" in str(v) else "⏭️"
            print(f"  {icon} {k}: {v}")


if __name__ == "__main__":
    main()
